### ISSUE TITLE
change false to sheker

### ISSUE THREAD

**Issue by greatjack1** [schorrm/ypp#2]
Currently false is undefined in yid++ and may result in yidden chas veshalom using the goyish version.

I think we should redefine it to sheker?

Hargoshos?

**Comment by schorrm** [comment]
Not shayich. A Ben Torah should use “nisht emes”, not “sheker”.
Give it a spin, by the way. Try compiling a file with “false” in it. Look at the error the compiler gives.

**Comment by achasveachas** [comment]
Gevaldig! Yasher Koiach for being mezake the rabbim with Ma'amorei Chazal right in our terminals!

**Comment by greatjack1** [comment]
ich her, shkoiach

**Comment by phooBarred** [comment]
> Gevaldig! Yasher Koiach for being mezake the rabbim with Ma'amorei Chazal right in our terminals!

A terminal is zicher a shtender.
